name: Dev CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


jobs:

  build:

    name: Build
    
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload APK File
        uses: actions/upload-artifact@v2
        with: 
          name: APK File
          path: app/build/outputs/apk/
